baseurl: /wax2
collections:
  New Collection:
    images:
      source: raw_images/New Collection
    layout: qatar_item
    metadata:
      source: New Collection.csv
    output: true
  annotations:
    output: true
    permalink: /annotations/:name
  collectionname:
    images:
      source: raw_images/collectionname
    layout: qatar_item
    metadata:
      source: collectionname.csv
    output: true
  exhibits:
    output: true
  qatar:
    images:
      source: raw_images/qatar
    layout: qatar_item
    metadata:
      source: qatar.csv
    output: true
  test:
    images:
      source: raw_images/test
    layout: generic_collection_item
    metadata:
      source: test.csv
    output: true
  test_collection:
    images:
      source: raw_images/test_collection
    layout: qatar_item
    metadata:
      source: test_collection.csv
    output: true
  testing_run1:
    images:
      source: raw_images/testing_run1
    layout: qatar_item
    metadata:
      source: testing_run1.csv
    output: true
copyright: Example copyright org, 2019
description: Minimal Exhibitions with Jekyll
exclude:
- Gemfile*
- Rakefile
- vendor
- spec
- README.md
footer:
  links:
  - label: GitHub
    link: https://github.com/minicomp/wax
  - label: Credits
    link: /credits
  - label: Contact
    link: https://gitter.im/minicomp/wax/
  logos:
  - img: /img/logo.png
incremental: true
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_backlink: '&#x21a9;&#xfe0e;'
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
logo: /assets/logo.png
menu:
- label: About
  sub:
  - label: Wax
    link: /about/
  - label: Documentation
    link: https://minicomp.github.io/wiki/wax/
  - label: Credits
    link: /credits/
- label: Exhibits
  sub:
  - label: Inline Parallax Image
    link: /exhibits/a/
  - label: Inline Image References
    link: /exhibits/b/
- label: Browse
  link: /collection/
- label: Search
  link: /search/
- label: Reuse
  link: /reuse/
permalink: pretty
sass:
  style: compressed
search:
  main:
    collections:
      collectionname:
        content: false
        fields:
        - pid
        - artist
        - location
        - label
        - _date
        - object_type
        - test_field
        - current_location
        - source
        - order
      qatar:
        content: false
        fields:
        - artist
        - location
        - label
        - _date
        - object_type
        - current_location
      test_collection:
        content: false
        fields:
        - pid
        - artist
        - location
        - label
        - _date
        - object_type
        - test_field
        - current_location
        - source
        - order
      testing_run1:
        content: false
        fields:
        - pid
        - artist
        - location
        - label
        - _date
        - object_type
        - test_field
        - current_location
        - source
        - order
    index: /search/index.json
title: Wax
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
